DELETE FROM products;
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`)
 VALUES ('GNdNXmlm','Corfu Coffee','corfu_coffee','Tchibo',6900);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('VLqdlJqA','Chai Latte','chai_latte','Franck (company)',2700);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('MMS83mf0','Australian Coffee ','australian_coffee','Gevalia',3700);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('CTlYPMYW','Irish Coffee ','irish_coffee','Barcaffe',3500);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('n1MMNc89','Kaffee Fertig ','kaffee_fertig','Flocafé',3700);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('TEkO8zPA','Kopi susu','kopi_susu','Nescafé',13800);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('v4CM8ZJu','Doppio','doppio','Massimo Zanetti Beverage Group',1800);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('hoRApgUW','Cold Brew Coffee','cold_brew_coffee','Manhattan Special',7600);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('1QfJBCDb','Black tie','black_tie','Diedrich Coffee',2900);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('UpOnekYd','Caffe Creama','caffe_creama','Caribou Coffee',4000);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('Wd449Ca7','Carajillo','carajillo','Coffee Alley',6800);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('1uswOxtp','Cafe au lait','cafe_au_lait','Keurig Dr Pepper',3800);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('hihOeHW3','Espresso con panna','espresso_con_panna','Trung Nguyên',14300);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('KAzSuMLQ','Jamaican Coffee ','jamaican_coffee','Costa Coffee',9000);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('paabstGc','Keoke Coffee ','keoke_coffee','Gaggia',2100);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('JaTcHK8J','Cafe Cubano','cafe_cubano','Gaviña Gourmet Coffee',4500);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('DdRw3vAK','Caffé Latte','caffé_latte','Ellis Coffee Company',12900);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('kqvaQ3tO','Cafe mocha','cafe_mocha','Dunn Brothers Coffee',2000);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('mGwxIgaj','Kopi Luwak','kopi_luwak','Gregorys Coffee',6400);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('ZELg65zE','Egg coffee','egg_coffee','Café Bustelo',6800);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('PnD1WP9z','Frappuccino','frappuccino','Juan Valdez',8700);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('a4844gqe','Coffee milk','coffee_milk','Löfbergs',4200);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('pVphMXrr','Cappuccino','cappuccino','Hills Bros. Coffee',12300);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('RNVPen1w','Liqueur coffee','liqueur_coffee','Caffe Bene',6000);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('SMMuez53','The Flat White','the_flat_white','Chase & Sanborn Coffee Company',6500);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('9T7ieNTz','Monks Coffee ','monks_coffee','Horn & Hardart',10700);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('J5bWZQ4Y','Café mélange','café_mélange','Hogood Coffee',8200);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('lxUgW9GQ','Indian filter coffee','indian_filter_coffee','FrancisFrancis',5400);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('lCZcqjZK','Macchiato','macchiato','Jamaican Blue Mountain Coffee',5600);
INSERT INTO `products`(`product_key`, `name`, `url`, `manufacturer`, `price`) VALUES ('53c2A5yr','Caffé macchiato','caffé_macchiato','UCC Ueshima Coffee Co.',14500);